version: '3.9'
services:
  db:
    image: postgres:16
    container_name: osmo_postgres
    restart: always
    environment:
      POSTGRES_USER: osmo
      POSTGRES_PASSWORD: osmo_test
      POSTGRES_DB: osmodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
